name: Generate Contribution Animations

on:
  schedule:
    - cron: "0 */12 * * *" # runs twice daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Animations
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate Matrix Animation
        uses: Platane/snk@v3
        with:
          github_user_name: PranaavKumar
          outputs: |
            dist/github-contribution-matrix-snake.svg?color_snake=#39FF14&color_dots=#0F0F0F
            dist/github-contribution-tetris.svg?palette=github-dark
            dist/github-contribution-blockchain.svg?palette=blue-pink

      - name: Push Generated Files
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
